
services:
    mailhog:
        build: 
            context: image
            args:
            #    - VALUE_MAILHOG_VERSION=v1.0.0
                - VALUE_UBUNTU_VERSION=latest
        container_name: test_mailhog
        restart: always
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/mailhog
        ports:
            - 8030:8025
