
services:
    mailhog:
        build: 
            context: image
            #args:
            #    - VALUE_MAILHOG_VERSION=v1.0.0
        container_name: test_mailhog
        restart: always
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/mailhog
        #tty: false
        #privileged: false
        #environment:
        #    - MH_STORAGE=maildir
        volumes:
            #- ./mailhog:/mailhog
            - ./data:/docker-entrypoint-initdata.d/
        ports:
            - 8030:8025
